log:
  logName: ./api.log
  outType: all
  formatter: txt
  level: debug

logmon:
  logPath: ""
  endpoint: "http://localhost:5080"
  user: "{{.ENV_OO_USER}}"
  password: "{{.ENV_OO_TOKEN}}"
  org: "default"
  stream: "service"
  maxSize: 2
  monitorSys: true
  cpuCron:  "*/5 * * * * * *"
  memCron:  "*/5 * * * * * *"
  diskCron: "*/5 * * * * * *"
  diskPath: "/dev/vda1"

# pprof:
#   host: 0.0.0.0:8080
#   enable: true



