version: '3'
# openobserve 部署与操作
vars:
  GREETING: Hello, World!
  SUP_CLI: "/root/supervisor/supervisord ctl -c /root/supervisor/supervisor.conf --env-file /root/supervisor/conf.d/.env"

tasks:
  deploy:
    - cmd: ssh root@{{.HOST}} "mkdir openobserve"
      ignore_error: true
    - cmd: ssh root@{{.HOST}} "mkdir -p openobserve/log"
      ignore_error: true
    - echo "openobserve mkdir"
    - ssh root@{{.HOST}} "cd openobserve && curl -L https://raw.githubusercontent.com/openobserve/openobserve/main/download.sh | sh"
    - echo "openobserve install success"
  
  initConfig:
    - scp ./deploy/assets/supervisor/openobserve.conf root@{{.HOST}}:/root/supervisor/conf.d/openobserve.conf 
    - scp ./deploy/assets/.env root@{{.HOST}}:/root/supervisor/conf.d/.env
    - ssh root@{{.HOST}} "{{.SUP_CLI}} reload"

  start:
    - task: initConfig
    - ssh root@{{.HOST}} "{{.SUP_CLI}} start openobserve"

  stop:
    - ssh root@{{.HOST}} "{{.SUP_CLI}} stop openobserve" 
  


