# https://taskfile.dev

version: '3'

dotenv: ['./.env']


vars:
  # HOST: dev.zuoshiyan.cn
  GREETING: Hello, World!
  VERSION: 0.0.0
  PROJECT_NAME: goservice
  GO_VERSION: 1.23.3



includes:
  dev:
    taskfile: ./task/dev/Taskfile.yml
  debug:
    taskfile: ./task/debug/Taskfile.yml
  deploy:
    taskfile: ./task/deploy/Taskfile.yml
  sv:
    taskfile: ./task/deploy/supervisor.yml
  oo:
    taskfile: ./task/deploy/openobserve.yml
  docker:
    taskfile: ./task/deploy/docker.yml
  mon:
    taskfile: ./task/deploy/monitor.yml
  hey:
    taskfile: ./task/debug/hey.yaml

tasks:
  default:
    cmds:
      - echo "{{.ENV_HOST}}"
    # silent: true
  devm:
    dir: ./cmd/service
    cmds:
      - go run -race -tags=forceposix main.go {{.CLI_ARGS}}
  lint:
    cmds:
      - golangci-lint run




