# https://taskfile.dev

version: '3'

dotenv: ['./.task-env']


vars:
  # HOST: dev.zuoshiyan.cn
  GREETING: Hello, World!
  VERSION: 0.0.0
  PROJECT_NAME: goservice
  GO_VERSION: 1.23.3



includes:

  super:
    dir: ./deploy/supervisord
    taskfile: ./deploy/supervisord/task-supervisor.yml
  oo:
    dir: ./deploy/openobserve
    taskfile: ./deploy/openobserve/task-openobserve.yml
  sermon:
    dir: ./deploy/service_monitor
    taskfile: ./deploy/service_monitor/task-monitor.yml
  api:
    dir: ./deploy/api_app
    taskfile: ./deploy/api_app/task-app.yml
  apilog:
    dir: ./deploy/applog_monitor
    taskfile: ./deploy/applog_monitor/task-applog.yml
  
  dockerdb:
    dir: ./deploy/docker_db
    taskfile: ./deploy/docker_db/task-dockerdb.yml

  dev:
    taskfile: ./task/task-dev.yml
  debug:
    taskfile: ./task/task-debug.yml
  build:
    taskfile: ./task/task-build.yml
  hey:
    taskfile: ./task/task-hey.yaml

tasks:
  default:
    cmds:
      - echo "{{.ENV_HOST}}"
    # silent: true
  devm:
    dir: ./cmd/service
    cmds:
      - go run -race -tags=forceposix main.go {{.CLI_ARGS}}
  lint:
    cmds:
      - golangci-lint run




