version: '3'
# openobserve 部署与操作
vars:
  GREETING: Hello, World!
  SUP_CLI: "/root/supervisor/supervisord -c /root/supervisor/supervisor.conf ctl"
  SER_ROOT: "/root/openobserve"

tasks:
  deploy:
    - cmd: ssh root@{{.SER_HOST}} "mkdir {{.SER_ROOT}}"
      ignore_error: true
    - cmd: ssh root@{{.SER_HOST}} "mkdir -p {{.SER_ROOT}}/log"
      ignore_error: true
    - echo "openobserve mkdir"
    - ssh root@{{.SER_HOST}} "cd openobserve && curl -L https://raw.githubusercontent.com/openobserve/openobserve/main/download.sh | sh"
    - echo "openobserve install success"
  
  upConfig:
    - scp ./openobserve.super.conf root@{{.HOST}}:{{.SUPER_CONFIG_ROOT}}/openobserve.conf

  start:
    - task: upConfig
    - ssh root@{{.SER_HOST}} "{{.SUP_CLI}} start openobserve"

  stop:
    - ssh root@{{.SER_HOST}} "{{.SUP_CLI}} stop openobserve" 
  


