# 命令执行 docker-compose -f docker-compose.yml up -d
networks:
  goservice:
    driver: bridge    

services:
  mysql:
    image: docker.io/library/mysql:8.0.32
    container_name: goservice_mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_PASSWORD}
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
    networks:
      - goservice
    ports:
      - "13306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 512M

  # phpmyadmin https://hub.docker.com/_/phpmyadmin

  mysqladmin:
    image: docker.io/adminer:latest
    container_name: goservice_adminer
    restart: always
    ports:
      - "10001:8080"  
    environment:
      - ADMINER_DEFAULT_SERVER=mysql  # 连接到mysql服务
      - ADMINER_DESIGN=nette  # 可选主题
    networks:
      - goservice
    depends_on:
      - mysql



  # 配置密码的情况下，volumes 添加 ./redis/users.acl:/usr/local/etc/redis/users.acl redis.conf 需要补充 aclfile /usr/local/etc/redis/users.acl
  redis:
    image: docker.io/library/redis:7.2.0
    container_name: goservice_redis
    restart: always
    hostname: redis
    ports:
      - 16379:6379
    volumes:
      - ./data/redis:/data
#      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
#    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - goservice
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3


  redis-admin:
    image: docker.io/rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    ports:
      - "10002:8081"
    environment:
      - REDIS_HOSTS=redis  # 使用服务名连接
      - REDIS_PORT=6379
      - HTTP_USER=${ENV_REDIS_ADMIN_USER}    # 可选认证
      - HTTP_PASSWORD=${ENV_REDIS_ADMIN_PASSWORD}
      - NO_LOGS=false     # 显示日志
    depends_on:
      - redis
    networks:
      - goservice