log:
  logName: ./log/logmon.log
  outType: all
  formatter: txt
  level: debug

logmon:
  logPath: "./log/api.log"
  endpoint: "http://localhost:5080"
  user: "{{.ENV_OO_USER}}"
  password: "{{.ENV_OO_TOKEN}}"
  org: "default"
  stream: "api"
  maxSize: 10
  monitorSys: false
  cpuCron:  "*/10 * * * * * *"
  memCron:  "*/10 * * * * * *"
  diskCron: "*/10 * * * * * *"
  diskPath: "/dev/vda1"