root: ./
log:
  logName: ./log/api.log
  outType: all
  formatter: json
  level: debug

mysql:
  user: root
  password: "{{.ENV_MYSQL_PASSWORD}}"
  host: 127.0.0.1:13306
#  host: mysql:3306
  dbName: goservice
  logFile:
  logLevel: 4

redis:
  addr: 127.0.0.1:16379
  password: {{.ENV_REDIS_PASSWORD}}
  db: 0

api:
  host: 0.0.0.0:8889
  openGinLog: true
  viewDir : ./view
  mode: debug
  domain: ""


pprof:
  host: 0.0.0.0:8080
  enable: false

jwt:
  secret: "{{.ENV_JWT_SECRET}}"
  # 3天过期时间
  exp: 259200

